# GET http://localhost:5237/api/Usuario/dajwdja1


POST http://localhost:5237/api/Usuario/Add
content-type: application/json

{
    "CURP":"SECS030711MJCGRFA0",
    "Nombre":"Sofia",
    "Apellido_P":"Segoviano",
    "Apellido_M":"Corona",
    "Cumpleanos":"2003-07-11T00:00:00",
    "Contrasena":null,
    "Autorizada":0,
    "Nom_Usuario":null
}